net/mosquitto: fix upstream mistake
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: etc/rc.d/mosquitto
===> Error: Plist issues found.